const Data = [
    {
        sku : "Black T-shirt",
        impressions:1234,
        clicks:121,
        spend:232,
        orders:3,
        sales:1000,
        subRows :[ {
            sku : "Google",
            impressions:134,
            clicks:121,
            spend:232,
            orders:3,
            sales:10,
        },
         {
            sku : "Amazon",
            impressions:134,
            clicks:121,
            spend:232,
            orders:3,
            sales:10,
        },
         {
            sku : "Facebook",
            impressions:134,
            clicks:121,
            spend:232,
            orders:3,
            sales:10,
        },
         {
            sku : "Walmart",
            impressions:134,
            clicks:121,
            spend:232,
            orders:3,
            sales:10,
        },
         {
            sku : "Tiktok",
            impressions:134,
            clicks:121,
            spend:232,
            orders:3,
            sales:10,
        },
         {
            sku : "Criteo",
            impressions:134,
            clicks:121,
            spend:232,
            orders:3,
            sales:10,
        }]
    },
    {
        sku : "Red T-shirt",
        impressions:1234,
        clicks:121,
        spend:232,
        orders:3,
        sales:1000,
        subRows :[ {
            sku : "Google",
            impressions:134,
            clicks:121,
            spend:232,
            orders:3,
            sales:10,
        },
         {
            sku : "Amazon",
            impressions:134,
            clicks:121,
            spend:232,
            orders:3,
            sales:10,
        },
         {
            sku : "Facebook",
            impressions:134,
            clicks:121,
            spend:232,
            orders:3,
            sales:10,
        },
         {
            sku : "Walmart",
            impressions:134,
            clicks:121,
            spend:232,
            orders:3,
            sales:10,
        },
         {
            sku : "Tiktok",
            impressions:134,
            clicks:121,
            spend:232,
            orders:3,
            sales:10,
        },
         {
            sku : "Criteo",
            impressions:134,
            clicks:121,
            spend:232,
            orders:3,
            sales:10,
        }]
    },
    {
        sku : "Pink T-shirt",
        impressions:1234,
        clicks:121,
        spend:232,
        orders:3,
        sales:1000,
        subRows :[ {
            sku : "Google",
            impressions:134,
            clicks:121,
            spend:232,
            orders:3,
            sales:10,
        },
         {
            sku : "Amazon",
            impressions:134,
            clicks:121,
            spend:232,
            orders:3,
            sales:10,
        },
         {
            sku : "Facebook",
            impressions:134,
            clicks:121,
            spend:232,
            orders:3,
            sales:10,
        },
         {
            sku : "Walmart",
            impressions:134,
            clicks:121,
            spend:232,
            orders:3,
            sales:10,
        },
         {
            sku : "Tiktok",
            impressions:134,
            clicks:121,
            spend:232,
            orders:3,
            sales:10,
        },
         {
            sku : "Criteo",
            impressions:134,
            clicks:121,
            spend:232,
            orders:3,
            sales:10,
        }]
    },
    {
        sku : "Gray T-shirt",
        impressions:1234,
        clicks:121,
        spend:232,
        orders:3,
        sales:1000,
        subRows :[ {
            sku : "Google",
            impressions:134,
            clicks:121,
            spend:232,
            orders:3,
            sales:10,
        },
         {
            sku : "Amazon",
            impressions:134,
            clicks:121,
            spend:232,
            orders:3,
            sales:10,
        },
         {
            sku : "Facebook",
            impressions:134,
            clicks:121,
            spend:232,
            orders:3,
            sales:10,
        },
         {
            sku : "Walmart",
            impressions:134,
            clicks:121,
            spend:232,
            orders:3,
            sales:10,
        },
         {
            sku : "Tiktok",
            impressions:134,
            clicks:121,
            spend:232,
            orders:3,
            sales:10,
        },
         {
            sku : "Criteo",
            impressions:134,
            clicks:121,
            spend:232,
            orders:3,
            sales:10,
        }]
    },
]
module.exports = {
    data : Data
}